### ISSUE TITLE
Error for downloading secondary data of WGBS

### ISSUE THREAD

**Issue by lifei176** [DavidQuigley/WCDT_WGBS#1]
Hi, 
I am exploring the DNA methylation profiles of CRPC and trying to download secondary data by using the folowing link: https://s3-us-west-2.amazonaws.com/feng.genomics/WGBS/secondary_data.zip. However, I always meet such error: 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8RQ3YDCTHPJ24A8A</RequestId>
<HostId>ySGAsagHzCO2ATDFIiNtoGNxfcuKxFsUvpKwzD5uoFl17aggr/PtfpMOia6sk6ca5tznNdcFHlo=</HostId>
</Error>.
Could you please help fix it?
Thank you very much.
Best regards,
Fei

**Comment by DavidQuigley** [comment]
Hi Fei, this has been fixed; there was apparently a permissions problem on AWS.
