### ISSUE TITLE
DNA Methylation CpG beta or m-values?

### ISSUE THREAD

**Issue by jarbet** [DavidQuigley/WCDT_WGBS#2]
Hello,

Are the patient-level whole genome DNA Methylation CpG beta-values (% methylated) or m-values made publicly available?  For example, are they contained in any of the files from the [Secondary Data](https://github.com/DavidQuigley/WCDT_WGBS#secondary-data) files?

Thanks!

EDIT:  I see that `/secondary_data/MethylSeekR` contains *regional* methylation data for PMD/non-PMD, and UMR/LMR regions identified from the MethylSeekR R package.  However, are the individual CpG beta-values made publicly available?

**Comment by DavidQuigley** [comment]
The CpG files are too large to host on GitHub; please get in touch with us directly.
