### ISSUE TITLE
Calculation of percent of the genome with DNA copy number alterations 

### ISSUE THREAD

**Issue by manjumoorthy95** [DavidQuigley/WCDT_WGBS#3]
Dear Team,

Thanks for making it public to understand the methods used to generate the plots presented in the publication. It helps a lot!

Is it possible to explain how was the % of the genomes per sample, which was copy number altered calculated?

**Comment by DavidQuigley** [comment]
The code we used to calculate % genome altered is re-used from our prior manuscript published in 2018 (Quigley et al. Cell 2018) as it analyzed the same patient samples. The relevant code is in the file https://github.com/DavidQuigley/WCDT/blob/master/scripts/prepare_data_for_secondary_analysis.R on and after line 906. 
Best regards,
David

**Comment by manjumoorthy95** [comment]
Thanks David for the clarification. 

Also wanted to ask how was the rHMR heatmap or figure 1C plotted? Because the HMR prediction from methylseekR for each sample would be across different regions/coordinates. So how was the Heatmap generated?

**Comment by DavidQuigley** [comment]
The code to generate all of the figures is in this repository; for Figure 1C, that can be found at
https://github.com/DavidQuigley/WCDT_WGBS/blob/master/scripts/2019_05_15_WGBS_figure_1C.R

**Comment by manjumoorthy95** [comment]
Ok Thanks for the information. I have already gone through that Script. So
kindly  correct me if I am wrong,  you have collected the common positions
of recurrent HMR across the samples and found the % of Methylation across
those positions and represented as a Heatmap.

Is that the method used? I got confused since methylseekr provides HMR
prediction for samples across different positions and not same position.
